sudo: required

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

notifications:
  email: false

services:
  - redis-server
  - docker

addons:
  apt:
    packages:
      - pkg-config
      - libattr1-dev
      - libfuse-dev

before_install:
  - docker run -v ~/ --name swift_data busybox
  - docker run -d --restart=always -p 12345:8080 --volumes-from swift_data -t morrisjobke/docker-swift-onlyone

install: "sudo pip install ."

cache:
  - pip
  - apt

script:
  - cd objectfs/tests/
  - pytest
